apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  type: NodePort
  selector:
    app: board
  ports:
    # 기본적으로 그리고 편의상 `targetPort` 는 `port` 필드와 동일한 값으로 설정된다.
    - port: 80
      targetPort: 8080
      nodePort: 30007